### ISSUE TITLE
Track GUI cut off

### ISSUE THREAD

**Issue by KadenBiel** [TeamOpenIndustry/ImmersiveRailroading#1016]
Whenever I use the track GUI the last few buttons are cut off by the bottom of the window if i'm in fullscreen. If I use windowed mode, I can get as far as the track gauge button but the last button has only a sliver showing at the bottom of the window. I'm using version 1.16.5 and I don't have anything other than this mod and the Track API installed

**Comment by robot256** [comment]
This happens on some screen resolutions because IR doesn't automatically scale or format the GUI to fit the screen.  To fix this, you have to go into the Minecraft Options -> Video Settings -> GUI Scale and manually set it to something other than Auto.

It would definitely be nice if the mod would figure this out automatically, or maybe change the layout to be wider and shorter.

(This has been an issue for so long I'm surprised it's not already in the GitHub issue list!)

**Comment by cam72cam** [comment]
I plan on re-designing the track GUI soon now that I have time
