### ISSUE TITLE
[Suggestion] Automation "enslavement" of the villagers

### ISSUE THREAD

**Issue by Cassiobsk8** [TeamOpenIndustry/ImmersiveRailroading#108]
It would be really cool if there was a way to automate the transport of fluids and items using a villager to drive the locomotive alone without the aid of a person in the style of that mod that was made for rails of war:
[ROWAM](https://mods.curse.com/mc-mods/minecraft/236585-rowam-rails-of-war-automation-module#t1:description)
so I could choose for him to stop and replenish the locomotive, empty the tank car and / or the vague items.
here is an image of inspiration for the water tank to load the locomotive with water:
[water tank](https://markpaulson.files.wordpress.com/2012/05/3841-12715352141.jpg)

thank's for your time.

**Comment by cam72cam** [comment]
The villagers idea is cool, I might integrate that into the mod

**Comment by Queglar** [comment]
Yeah ROWAM was definitely a bit mandatory for ROW - driving a train is all well and good the first time, but pretty quickly you just want to hire an engineer to do all the train driving according to a schedule rather than have to do everything yourself all the time. I think I actually spent more time in the passenger carriage than the engine. 

Main problem I had with ROW and ROWAM though was there were no lights in the carriage at night, but even worse, my villagers kept getting impatient and kept jumping on the tracks, rather than getting in the train. The mortality rate for my train line was rather high...
