### ISSUE TITLE
Coupler Physics to be Config file dependent

### ISSUE THREAD

**Issue by whatsapp2** [TeamOpenIndustry/ImmersiveRailroading#1379]
This suggestion comes from the #test-builds channel in discord, and would like to put it in this github just in case it's easier to keep track of it.

I'm using Immersive Railroading 1.9.1-32d9009 and Universal Mod Core 1.1.4-18c5c71 in a whitelisted server with some friends, we plan to open it to the public some time in the near future, and we where doing tests to see what IR version is the most stable to use. We found out that in this particular version of IR (latest test build in discord) we can't drive trains longer than 10 cars because at some point the train rubber bands and cars just decouple, flung off the train at very high speeds. Also trains can't be pushed from behind for the same reason, it rubber bands and cars just decouple. It acts very much like Traincraft physics right now.

The suggestion is to make coupler physics be a config dependent addition, so you can enable/disable when it doesn't want to work. When disabled it should behave like stable versions of IR, without the coupler slack and cushioning of cars.

**Comment by cam72cam** [comment]
What people call "coupler physics" is a complete rewrite of the physics system that makes it actually possible to work on, the "stable" one was collapsing under it's own weight.  This system will be refined over time and improved.  Instead of asking to revert it, please instead post specific scenarios (preferably videos) of scenarios that don't currently work well in the test builds.
