### ISSUE TITLE
Add research

### ISSUE THREAD

**Issue by FriedrichLP** [TeamOpenIndustry/ImmersiveRailroading#234]
So that you start off in like 1700 or so and get all the locos that existed in that time. And as time progresses you get more locos to research and later you would get the possibility to research diesel engines and so on! You could adjust the speed in wich time progresses in the config (default maybe 1 year per minecraft day). The researches could cost xp and stuff or xp and energy or something else! And make it so that you can still access all the locos fron creative or add a config option to disable the research thing!

**Comment by rongineering** [comment]
I just wanted to add some input on this as someone who plays with the mod on a custom, personal, survival pack. I love the idea of different level/tier/time-period locomotives being gated by a research based element. I do not however like the idea of a time based based research method (I could just leave my server up overnight or fiddle with another mod while I wait to unlock the Big Boy since that is like 90% of all I ever ride around in). I'm a big fan of resource and power related gating. My recommendation for a research based addition would be a research multiblock (something that looks train-station-y or locomotive-works-y) that requires x amount of resources, y amount of experience and z amount of power (RF in the spirit of IE) to advance to the next "age" of locomotive engineering. You could have it generate a blueprint item that is tied to the player (kind of like galacticraft rocket schematics) that is then inserted into the manual (think Astral Sorcery constellation storage) or something to unlock the components to create the next "level" of locomotive. 

Just my $.02

**Comment by FriedrichLP** [comment]
That are amazing ideas! I totally agree with everything you´ve said! Thx for the ideas

**Comment by cam72cam** [comment]
This would be something neat to play with for 2.0

**Comment by Xelbayria** [comment]
That's a very interesting idea. I liked the idea of using XP to gain some research and unlock new technologies to build a better locomotive, it will be fun to do that with slow progression!
I am looking forward to it!
