### ISSUE TITLE
Xelly's Rolling stock To Do List

### ISSUE THREAD

**Issue by Xelbayria** [TeamOpenIndustry/ImmersiveRailroading#292]
# **Standard Guage** 

**Locomotives**
- [ ] EMD F7A & Unit B (WIP)
- [ ] EMD E8 (after F7A)
- [ ] EMD SD45 (WIP)
- [ ] EMD SD45T-2 (after SD45)
- [ ] EMD ET44AC 
- [ ] Union Pacific GTEL 8500 
- [ ] Acela Express 
- [ ] Bombardier MP40PH-3C
- [ ] ICE 3

**Types of Passenger Cars**
- [ ] Bombardier Bi-Level Coach
- [ ] Amtrak Surfliner & Superliner
- [ ] Acela Express' passenger cars
- [ ] ICE 3's passengers

**Types of Freight Cars**
- [x] Lumber Car
- [x] Centerbeam / Center Partition Car (for planks) 
- [x] Bulkhead Car
~~- [ ] Tank Car~~

**Comment by MrSamPlays** [comment]
Is it possible to have some sort of control car (unpowered passenger car with driver controls) for a push-pull locomotive? It would be cool because then I won't have to design train turnaround loops that take up so much space

Here's some useful links as to what I'm talking about.
https://en.wikipedia.org/wiki/Push%E2%80%93pull_train
https://en.wikipedia.org/wiki/Control_car#/media/File:Amtrak_9636_leading_Keystone_Service_train_at_Elizabethtown,_August_2007.jpg
