### ISSUE TITLE
Modern Electrics [For 2.0 release][WIP Model List]

### ISSUE THREAD

**Issue by EliteDire4K** [TeamOpenIndustry/ImmersiveRailroading#293]
**Diesel Electrics**
A.E Goodwin 442-Class - 95% Complete

**Diesel Locomotives**
Intercity 225

**Bullet Trains** [Least Priority]
IBM100 - Uncertain [Can't Locate Proper Blueprints]
AGV Italo - Uncertain [Can't Locate Proper Blueprints]
Fuxing Bullet Train - Uncertain [Can't Locate Proper Blueprints]

**Requested**
Pennsylvania GG1 - On Hold [Very Difficult atm]

**Maglevs**
Transrapid (Shanghai Maglev Variant) On Hold

**Comment by rongineering** [comment]
Could I add a suggestion? The Pennsylvania GG1

**Comment by EliteDire4K** [comment]
> Could I add a suggestion? The Pennsylvania GG1

I think this was already done as part of the base pack.

**Comment by JazzTheAmazing** [comment]
As of current, modelling has been halted due to non functioning mouse and university life. I am in the process of requiring a better mouse for modeling to complete the 442 Goodwin and the ice 1. These models are near completion for modeling. I am unable to test them in game due to my systems lack of power to even run minecraft stable, however i am working on getting the models tested by a friend. [All Request would be fulfilled as soon as possible.

**Comment by EliteDire4K** [comment]
AE 442 model nearly completed, sorry for long absence. Personal stuff came up and had to be dealth with also needed a new mouse. 
![image](https://user-images.githubusercontent.com/38272276/83952965-b6e7b800-a80a-11ea-8f34-54595406c6bf.png)

![image](https://user-images.githubusercontent.com/38272276/83952978-cbc44b80-a80a-11ea-96a5-7b30eab42a6b.png)

![image](https://user-images.githubusercontent.com/38272276/83952994-dbdc2b00-a80a-11ea-9bec-c877b0a06fa2.png)
