### ISSUE TITLE
[suggestion] Some other suggestions

### ISSUE THREAD

**Issue by VioletWyvern** [TeamOpenIndustry/ImmersiveRailroading#582]
This mod was fun when you driving a realistic train, But it can be some more improvements:

1. An **"Easy Driving"** mode 
      For now, the trains control has two gauges: Throttle and Brakes, But some players think this was a little bit too complicated,  They wants a simplified mode to control the train...
My suggestion is this: Making train has only Throttle gauge on it's gui,  When Easy Driving mode was set to on, When trains throttle up, It will slowly going up at designated speed **(No more spinning wheels)** and maintain on it **(Train will not going faster and faster)** And when throttle down, Train will auto braking and slow down to the designated speed **(No more overrun the station)**...
Finally, Making this feature been toggle-able via config file,  If player like or dislike it, They can switch back to the normal control mode from here...

2. Rail Augments needs gui: 
     The rail augments is very difficultly to figured out how to set them up now, Because it's lacks of information to showing the current status ,   Also... can only been toggled by redstone signal was a bad idea.... (Why don't just making a gui and set the current status to tell the train how to do?)
 
3. Cross-mod Supports:
    It's seem this mod was not support other mod that using minecart api **(Such as Railcraft)** , So we can't set up some signal network to detect and maintaining tracking the train...  Maybe some cross-mod support will coming in handy...

4. Entities on flat cars:
    At now, Flat cars just like other boxcar _(Riding on and stored some items)_, This was a little wasting the flat car's purpose _(It's was design for transport large objects that too big for boxcars)_, And at now, We can only using whistles to let villagers boarding the train,  Must has some other ways to let some non-villager entities _(Such like other vehicles from other mods)_ boarding the train...

**Comment by FriedrichLP** [comment]
1. I think there won't be an "easy driving mode" of that kind just because the current system is already incredibly unrealistic and easy to use. I mean even a banana would be able to learn how to use the current system. There is a much more realistic system planned but for that case the current one can be toggled using the config.

2. That's a nice idea but for now you can just take a look at the wiki because it explains every argument in detail.

3. We already have an addon made by CSX8600 which adds signals for train detection. But I think we could add more support for stuff like that in the future.

4. That's already possible. You can put the entity on a leash and then right-click the freight car with it!

**Comment by VioletWyvern** [comment]
I know you can mount the entity on the freight cars,  But for the entities that cannot using leashes? 
**(Ex: _Hostile mobs_, Other mods entities, _Mutiblock entities like cars, trucks, etc..._ )**

**Comment by 4gyanyuan** [comment]
To make the tracks efficiently, i hope those machines have entrances and exports with clear sign.

**Comment by cam72cam** [comment]
Closing as won't fix
