### ISSUE TITLE
Add joystick control

### ISSUE THREAD

**Issue by Excited-Naive** [TeamOpenIndustry/ImmersiveRailroading#595]
Then using joystick to control IR trains is possible (just like IV) and can have better driving experience, and if IR can export speed data out of the game to usb devices, then speedometer is possible too

**Comment by EScapeTheShadows** [comment]
while the idea is neat, it will have to be put onto the back burner til advanced controls are in, due to the code only knowing when to zero slider, increase slider, and decrease slider. as a result, unless your willing to constantly fiddle with the joystick, this isn't currently possible. That being said, it is a neat idea to implement for advanced controls.

**Comment by km00700** [comment]
small problem. Advanced Diesel control will involve throttle notches. So a joystick will be pointless.
