### ISSUE TITLE
Trains are not visible in some viewing angels

### ISSUE THREAD

**Issue by xNccPlay** [TeamOpenIndustry/ImmersiveRailroading#704]
Today I installed the new 1.7.2 update on my 1.12.2 server (I was on 1.6.1 before) and noticed, that in some viewing angles, the interrior is completly disappearing, while standing still in a loco or any other rolling stock. But this isn't always the case. Sometimes everything is working fine. The problem also does appear on some trains while standing outside and look around.

Here are some screenshots. Each two are exactly the same spot just with an other viewing angel.

![2019-11-24_17 27 29](https://user-images.githubusercontent.com/1348874/69497649-d73fcd00-0edf-11ea-9972-6b01349a386f.png)
![2019-11-24_17 27 36](https://user-images.githubusercontent.com/1348874/69497650-d73fcd00-0edf-11ea-906d-cd48fea8394b.png)
![2019-11-24_17 27 47](https://user-images.githubusercontent.com/1348874/69497651-d73fcd00-0edf-11ea-801e-77dacdf689fc.png)
![2019-11-24_17 27 54](https://user-images.githubusercontent.com/1348874/69497652-d73fcd00-0edf-11ea-87f8-2e8445710fea.png)
![2019-11-24_17 32 20](https://user-images.githubusercontent.com/1348874/69497783-f4c16680-0ee0-11ea-9aee-6ec4e52e1e5b.png)
![2019-11-24_17 32 25](https://user-images.githubusercontent.com/1348874/69497784-f4c16680-0ee0-11ea-852b-598c1eaafae5.png)

Minecraft-Version: 1.12.2
Forge-Version: 14.23.5.2838
Mod-Version: 1.7.2

**Comment by Johni0702** [comment]
While looking for other stuff, I noticed this line:
https://github.com/TeamOpenIndustry/UniversalModCore/blob/bf8bd48513ab90eb6759c777e9a7efe91c40b6fd/src/main/java/cam72cam/mod/render/GlobalRender.java#L93
Not sure if that's intended (I didn't think about it much) but be aware that calling `new Frustum()` will break `Frustum`s which have previous been acquired via the same constructor (including the one used by MC itself) because it calls `ClippingHelperImpl.getInstance()` which has a bad name because it not just gets but also updates the `ClippingHelperImpl` singleton (had to learn this the hard way myself: https://github.com/Johni0702/BetterPortals/commit/ad1fa133c0d8397462a2037301db84b92c3c69f6).
Depending on when `getCamera` is called, I could imagine that leading to such issues.

**Comment by biauk** [comment]
I recommend not to use 1.7.X versions because they are very buggy. It's better to stay at 1.6.1.

**Comment by Snuggle** [comment]
Also having this issue on Forge Minecraft 1.14.4

**Comment by cam72cam** [comment]
Thanks @Johni0702
