### ISSUE TITLE
Locomotive Control doesn't work on long trains

### ISSUE THREAD

**Issue by jeffswt** [TeamOpenIndustry/ImmersiveRailroading#785]
**Describe the bug**  
Locomotive Control doesn't work on long trains
It works, but it won't go

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Build a sufficiently long track
 2. Concatenate 1 SW1500 (diesel engine) and 6 BR coach MK1 (passenger stock)
 3. Stick a locomotive control right under the engine, set to "Throttle forward" mode and light it with a redstone signal.
 4. The diesel engine is fully throttled now (if you enter it you can see that it is on the dashboard), and it makes louder engine noises - however the train does not move
 5. Changing the locomotive control augment to "horn" mode, and the train can be moved by manually throttling the engine.
 6. Reducing the number of <BR coach MK1> passenger cars to 2 (or 3) and repeating the aforementioned steps will, as expected, result in the train moving upon redstone signal activation.
 
**Expected behavior**  
The train should move under the said case.

*This applies to all trains as long as they are long enough*

**Screenshots**  

**System Information**
 OS: Windows 10 64-bit
 <br>System Memory: 8 GiB
 <br>Allocated Memory: 6 GiB
 <br>CPU: Intel i7-6700HQ
 <br>GPU: Nvidia GTX 950m
 <br>IR-Version: 1.7.3
 <br>Forge-Version: 1.12.2-14.23.5.2847

**Modlist**  
Just IR

**Comment by jeffswt** [comment]
Hypothesis: diesel engines cannot switch from forward to backward (and vice versa) without zeroing the speed with neutral gears first. I wonder whether this might be the reason the bug is here.

**Comment by km00700** [comment]
Since IR doesn't currently simulate any gearing for diesel engines, I can nullify that hypothesis out the gate. If you're applying full redstone power, then what's likely happening is that you're getting wheelslip. The signal strength of the redstone is proportional to the throttle. If you put it at full power immediately, the wheels lose traction with the rail and you slip. If the load is lighter, you're less likely to slip. Hence the result you saw. So what you've seen is not actually a bug, but rather a result of the augments having a lot of control over the throttle. As a player, you're forced to let the throttle slide up over time. There are a few solutions. The easiest is to probably build a circuit that increases the signal strength gradually. If you want, you could also add more throttle augments and have successive ones each set the throttle a bit higher. the most difficult, is to use OpenComputers and program a script to gradually throttle up the locomotive.

**Comment by jeffswt** [comment]
So it's a feature, not a bug /Facepalm

Then it's related to weight I guess
