### ISSUE TITLE
Random Player Teleporting

### ISSUE THREAD

**Issue by Rysiek18** [TeamOpenIndustry/ImmersiveRailroading#811]
When train is placed somewhere in the world (It doesn't matter whether it is on or off) there is big chance that another players would teleport directly to this vehicle

**Comment by AveoCross** [comment]
Random teleporting also happens sometimes when someone mounts into train. Some players on my server experienced that already even when they are multiple thousands blocks away from that train.

**Comment by cam72cam** [comment]
Fixed in the test-builds, will be in the next release.

**Comment by TheFlash787** [comment]
Hey @cam72cam - Do you know when this was fixed? I can't find the specific commit for this but would like to backport the fix into the 1.7.3 version for our server.

**Comment by Larky2k** [comment]
update to latest build

**Comment by TheFlash787** [comment]
> 
> 
> update to latest build

I understand that. This isn't my move to make. As part of the Chroma Technology modpack they are running the 1.7.3 version and I would like to patch this inside of the existing version in preparation for the 1.8.0 update.

I would like to know the commit that this issue was fixed inside of, as that particular commit doesn't look to have referenced this issue page (as it normally would) so that I can do the dirty work myself and patch it inside of the 1.7.3 build. As a public server developer for a pre-existing modpack, we unfortunately cannot update mod versions inside of the modpack as it is not our move to make.

If you can find the commit that this issue was fixed from, I would really appreciate it. :)

**Comment by Larky2k** [comment]
just get the people who make the pack to update it be alot less hassel then the ass about way you want to do it cause then other people will need said patch as well which at that point you just get people to update to latest version

**Comment by TheFlash787** [comment]
Hey there.

That's not my responsibililty I'm afraid. My responsibililty is our server, and I'd like to get this issue fixed. It will be a lot less hassle to port over the fix than trying to pursuade a pack author to update the mod in a release that may not come out for weeks.

If you would be able to find this commit, I'd be forever in your debt, otherwise no worries.

**Comment by Larky2k** [comment]
its not going to be that easy as IR which in 1.7.3 had UMC in it  separated in 1.8+ so its split across 2 mods
