### ISSUE TITLE
[Enhancement] HexaCord/Waterfall/Travertine support

### ISSUE THREAD

**Issue by CuzImDestroyer** [TeamOpenIndustry/ImmersiveRailroading#815]
**What the suggestion is about:**

Our server network wants to make one lobby for all our train servers, so we want to have BungeeCord support. Note, that we don't use the normal Bungee, we use Travertine. So the problem occured was, that we have problems at entering vehicles. This is due to the server being in offline mode, but the Bungee network being in online mode. So packets do corrupt somehow. By the time, MTS (IV) and FVTM had the same issue, Ferdinand/Fexcraft and myself fixed it there on testing with different player checks (https://github.com/DonBruce64/MinecraftTransportSimulator/pull/463) and want to have that included also in IR. And yes, our network might be the minority use it, but it would help getting it resolved for further Bungee networks.

**What it changes:**

- Adding HexaCord/Waterfall/Travertine support
-> Drivable IR Trains

- Packet Handling doesn't require being in online mode

When questions occur, please message me via making a comment under this suggestion.

**Comment by Fexcraft** [comment]
Related:
- https://github.com/Fexcraft/FVTM/commit/f30d9552bd513cee420627dbb4c3e7eb58813838

This can be quickly fixed on a mod's side if it doesn't depend explicitly on the player ID.
Such can be archived with having separate packet handlers for server/client.
IIRC getting the player by id might been a fix to prevent the server/jvm from crashing due to missing classes
when using the same handler/class for both sides.

**Comment by cam72cam** [comment]
If I send the player's UUID and do a world lookup based on that, will it still cause problems @Fexcraft @CuzImDestroyer ?
