### ISSUE TITLE
Casting basin GUI doesn't remember gauge setting

### ISSUE THREAD

**Issue by hayesj1** [TeamOpenIndustry/ImmersiveRailroading#854]
**Describe the bug**  
A clear description of what the bug is.

**How to reproduce**  
Steps to reproduce the unwanted behavior:

 1. Open the casting basin gui
 2. select a item and choose a non-default guage
 3. open up the item selection gui again
 4. gauge is reset
 
**Expected behavior**  
Gauge to save my choice

**Screenshots**  

**System Information**  
 OS: Windows
 <br>System Memory: 32gb
 <br>Allocated Memory: [12gb
 <br>CPU: [e.g. "Intel I7 7700k"]
 <br>GPU: GTX 1660 TI
 <br>1.8-RC4-1.12.2
 <br>14.23.5.2844

**Modlist**  
 Provide a list of the mods you used. You can either directly write them in here or use an online service like https://pastebin.com/ and provide the link.
 
**latest.log**
 Provide the latest.log by going into your Modpack_folder/Logs, paste the contents of the file to an online service like https://pastebin.com/ and provide a link.

**Additional context**  
Provide any additional information that might help us fix the bug.

**Comment by cam72cam** [comment]
This is kind of a funny one.  The logic currently default's to the recommended gauge (if not model).  A lot of the modellers asked for this functionality so I'm kinda torn

**Comment by robot256** [comment]
When I'm playing survival, I rarely want to change the gauge of the casting basin because I don't change the gauge of my track very often (or ever).  It's good to know the recommended gauge for a model, but if I've decided it's worth using at a different gauge then it is indeed annoying to have to triple-check it every time.

**Comment by jhayes2-chwy** [comment]
I think have a good middle ground for this; default to the recommended setting for a stock, but then remember its setting as long as you don’t change the stock. This way the parts stay memo-ized, but if I switch to casting parts for some other stock it resets to the default. Also fixing the recommended gauge issue where everything “is” SG would help too. But Robot256, makes a very good point. I suggest make it a config option, because it’s good to have both ways one for productive modeling sessions, the other for actual playthroughs.
