### ISSUE TITLE
Detector Augment's Info Method Returns Incorrect Fluid Amount

### ISSUE THREAD

**Issue by andrewlalis** [TeamOpenIndustry/ImmersiveRailroading#925]
Using latest release versions of Immersive Railroading, Universal Mod Core, Track API.

Using the detector augment, call the `info()` method while a fluid tank rolling stock item is above it, and inspect the resulting table. You should see the `fluid_amount` value is always zero, despite the fact that the tank is in fact full.

![image](https://user-images.githubusercontent.com/9953867/106652824-490caf80-6596-11eb-919a-d1c71ede30b3.png)

![image](https://user-images.githubusercontent.com/9953867/106652837-4dd16380-6596-11eb-8943-7d3d06d8c094.png)

**Comment by latibro** [comment]
Seems like the code right now will always give

```lua
fluid_type = nil
fluid_amount = 0.0
```

because some code here is commented out [https://github.com/TeamOpenIndustry/ImmersiveRailroadingIntegration/blob/168b77071eecae209d3f19bcf348c2c47742eeb9/src/main/java/cam72cam/immersiverailroading/thirdparty/CommonAPI.java#L43](https://github.com/TeamOpenIndustry/ImmersiveRailroadingIntegration/blob/168b77071eecae209d3f19bcf348c2c47742eeb9/src/main/java/cam72cam/immersiverailroading/thirdparty/CommonAPI.java#L43)

Which will mean that getFluid() always return null, and the have the code at [https://github.com/TeamOpenIndustry/ImmersiveRailroadingIntegration/blob/168b77071eecae209d3f19bcf348c2c47742eeb9/src/main/java/cam72cam/immersiverailroading/thirdparty/CommonAPI.java#L97](https://github.com/TeamOpenIndustry/ImmersiveRailroadingIntegration/blob/168b77071eecae209d3f19bcf348c2c47742eeb9/src/main/java/cam72cam/immersiverailroading/thirdparty/CommonAPI.java#L97) always return nil and 0.0

**Comment by cam72cam** [comment]
It'll be fixed in the next release
