### ISSUE TITLE
Adaptor block missing

### ISSUE THREAD

**Issue by RaphaelCapone** [TeamOpenIndustry/ImmersiveRailroading#951]
Hello, I don't really know if this is a bug related to this mod or not(I mean I don't know if the Adaptor block comes from a 3rd party mod) but I am trying to automate a railway system following this tutorial from this mod wiki(https://github.com/TeamOpenIndustry/ImmersiveRailroading/wiki/Open-Computers) and I cannot find the Adaptor block.. .
I have installed the following mods:
- Immersive Railroading + Engineering + TrackAPI + UniversalModCore and CC-Tweaked(in replace for OpenComputers since it is not longer updated... [link](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)).
![image](https://user-images.githubusercontent.com/44115221/112231342-35e59a00-8c3f-11eb-8260-95ed64e0010a.png)
![image](https://user-images.githubusercontent.com/44115221/112231856-2fa3ed80-8c40-11eb-966a-1277bdfb202a.png)
Well..my question is, is the tutorial from the wiki for train automatization still working? If yes...why am I  not seeing the Adaptor block?Is there other depency mode for that? And if no, is there another way to automate the trains without Open Computers mod?
I also tried to follow this tutorial: https://youtu.be/dGER7-BI5Dw?t=237 (which is actually what I am trying to do)
Thank you! Any response will be highly appreciated! :-)

P.S: I'm sorry if my topic is poor in describing the problem, but my knowledge about minecraft mods is kind of small since I played occasionally this game..

**Comment by Doublehelix13** [comment]
The Adapter is added by Open Computers.  You don't have the Adapter because you don't have Open Computers.  That tutorial is specifically for Open Computers, as that is the best way to automate trains right now.  I think there is some compatibility with Immersive Railroading and CC Tweaked, but it's not as extensive as the compatibility for Open Computers.  Asking for help in the computers-automation channel in Immersive Railroading's Discord would be a good idea.
