### ISSUE TITLE
Icons in inventory are invisible

### ISSUE THREAD

**Issue by Elthagrim** [TeamOpenIndustry/ImmersiveRailroading#958]
Modlist: 

http://prntscr.com/115b6a1

I suspect it is some kind of incompatibility with the rendering that the Optifine causes.
Is there a solution other than uninstall it?

Some screnshots:

http://prntscr.com/115b8j5

http://prntscr.com/115b97b

**Comment by km00700** [comment]
1. Disable Optifine fast render.
2. Delete the cache folder in your .minecraft directory
3. Startup minecraft.

**Comment by Elthagrim** [comment]
Thanks its working.

**Comment by aitahon** [comment]
> 1. Disable Optifine fast render.
> 2. Delete the cache folder in your .minecraft directory
> 3. Startup minecraft.

That didnt work for me
Mods:
https://prnt.sc/19h0i9z

How it looks for me :
https://prnt.sc/19h0m1m

**Comment by Lasse2000** [comment]
I have tried out the mod in 1.16.5 and in 1.12.2 both either with optifine installed and the cache folder deleted and without any optifine, but I am still not able to see the trains in the inventory, which makes the navigation through the trains very laborious.

**Comment by Larky2k** [comment]
Clear your cache folder with fix it,  cache folder is in the instance of Minecraft your using.

**Comment by CptStormfur** [comment]
Hi, Lasse here, on a second account.
So the cache folder I've deleted was in .minecraft

But I've actually fixed the problem. As I was unintentionally browsing in the settings, I clicked randomly on "shaders" which then said "set Antialiasing on 0" and then I thought, that Immersive Railways may have the same problem with the Antialiasing, so that I set it on 0 and deleted the cache folder again. Then after starting minecraft again, it worked and now there is every icon in the Inventory.
